Added HTTP and HTTPS code examples
atapas/nodeX pull request #3
Opened 2022-03-07 19:13 UTC by Akshaya101

HTTP and HTTPS code examples have been added.

2022-03-08 04:14 UTC, atapas requested changes
@Akshaya101 

Here are some initial comments: https://github.com/atapas/nodeX/issues/1#issuecomment-1061387863

2022-03-09 19:41 UTC, Akshaya101 commented
HTTP module has been added. Let me know if any changes are to be made.

2022-03-10 03:51 UTC, atapas commented on http-module/code/write-head.js
> +    // res.writeHead(200, {
@Akshaya101 remove the commented code

2022-03-10 03:53 UTC, atapas commented
> HTTP module has been added. Let me know if any changes are to be made.

Thank you!

Can you please add an example for Create a https server as well as the PR says for both HTTP and HTTPS module? You can add a separate folder and readme for https like you did for http. Thanks a lot.

2022-03-10 15:09 UTC, Akshaya101 commented
HTTPS module has been added. Let me know if there are any changes to be made

2022-03-11 06:03 UTC, atapas commented
> HTTPS module has been added. Let me know if there are any changes to be made.

Thanks a lot, @Akshaya101. Looks great. It will help a lot of developers.

2022-03-11 06:06 UTC, atapas approved these changes
Thanks @Akshaya101 RTM

2022-03-11 06:06 UTC, merged